### ISSUE TITLE
script/plugin:3:in `require': no such file to load -- commands/plugin

### ISSUE THREAD

**Issue by exceptionraiser** [jm/rails_upgrade#19]
When I try and run `script/plugin install git://github.com/rails/rails_upgrade.git` I get this:

```
script/plugin:3:in `require': no such file to load -- commands/plugin (LoadError)
    from script/plugin:3
```

Not sure that to do with this. Any thoughts? Thanks!

**Comment by exceptionraiser** [comment]
Ok so I was able to install it doing `git clone -q git://github.com/rails/rails_upgrade.git`

But no when I try to run the rake commands I get this:

```
app:rake rails:upgrade:check
rake aborted!
undefined method `merge_joins' for class `Class'

(See full trace by running task with --trace)
app:rake rails:upgrade:check --trace
rake aborted!
undefined method `merge_joins' for class `Class'
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.9/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method'
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.9/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method_chain'
/Library/Ruby/Gems/1.8/gems/searchlogic-2.4.28/lib/searchlogic/active_record/consistency.rb:8:in `included'
/Library/Ruby/Gems/1.8/gems/searchlogic-2.4.28/lib/searchlogic/active_record/consistency.rb:7:in `class_eval'
/Library/Ruby/Gems/1.8/gems/searchlogic-2.4.28/lib/searchlogic/active_record/consistency.rb:7:in `included'
/Library/Ruby/Gems/1.8/gems/searchlogic-2.4.28/lib/searchlogic.rb:34:in `include'
/Library/Ruby/Gems/1.8/gems/searchlogic-2.4.28/lib/searchlogic.rb:34
/Library/Ruby/Gems/1.8/gems/bundler-1.0.21/lib/bundler/runtime.rb:68:in `require'
/Library/Ruby/Gems/1.8/gems/bundler-1.0.21/lib/bundler/runtime.rb:68:in `require'
/Library/Ruby/Gems/1.8/gems/bundler-1.0.21/lib/bundler/runtime.rb:66:in `each'
/Library/Ruby/Gems/1.8/gems/bundler-1.0.21/lib/bundler/runtime.rb:66:in `require'
/Library/Ruby/Gems/1.8/gems/bundler-1.0.21/lib/bundler/runtime.rb:55:in `each'
/Library/Ruby/Gems/1.8/gems/bundler-1.0.21/lib/bundler/runtime.rb:55:in `require'
/Library/Ruby/Gems/1.8/gems/bundler-1.0.21/lib/bundler.rb:122:in `require'
/Users/marclipovsky/Sites/Volunteer/app/config/application.rb:7
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
/Users/marclipovsky/Sites/Volunteer/app/Rakefile:4
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:501:in `raw_load_rakefile'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:82:in `load_rakefile'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:81:in `load_rakefile'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:65:in `run'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/bin/rake:33
/usr/bin/rake:19:in `load'
/usr/bin/rake:19
app:
```

Now i'm really not sure what todo. Any help would be greatly appreciated. Thanks!

**Comment by exceptionraiser** [comment]
I commented out `Bundler.require(:default, Rails.env) if defined?(Bundler)` in my application.rb file and the rake command worked... But I feel like that's not a long term solution. Any thoughts?

**Comment by aiTheFirst** [comment]
Hi @marclipovsky, were you able to sort this out? Having the same issue and no luck despite several attempts. hearing back would be greatly appreciated!

**Comment by exceptionraiser** [comment]
@artfulgeek Dang... I don't even remember what I did now. It's been too long. Sorry. If I find what I did I'll be sure to post it here for sure.
