### ISSUE TITLE
error generating routes with map.root

### ISSUE THREAD

**Issue by tardate** [jm/rails_upgrade#6]
Testing a migration on a very small/simple 2.3.5 site, rake rails:upgrade:routes fails with map.root in the routes file, e.g.

  map.root :articles

Commenting this out, routes generation is ok.

  $ rake rails:upgrade:routes --trace
  (in /Users/paulgallagher/MyGithub/heroku/rails-authlogic-rpx-sample)
  *\* Invoke rails:upgrade:routes (first_time)
  *\* Execute rails:upgrade:routes
  rake aborted!
  undefined method `[]' for :articles:Symbol
  /Users/paulgallagher/MyGithub/heroku/rails-authlogic-rpx-sample/vendor/plugins/rails_upgrade/lib/tasks/../../lib/routes_upgrader.rb:237:in`to_route_code'
  /Users/paulgallagher/MyGithub/heroku/rails-authlogic-rpx-sample/vendor/plugins/rails_upgrade/lib/tasks/../../lib/routes_upgrader.rb:337:in `generate'
  /Users/paulgallagher/MyGithub/heroku/rails-authlogic-rpx-sample/vendor/plugins/rails_upgrade/lib/tasks/../../lib/routes_upgrader.rb:336:in`map'
  /Users/paulgallagher/MyGithub/heroku/rails-authlogic-rpx-sample/vendor/plugins/rails_upgrade/lib/tasks/../../lib/routes_upgrader.rb:336:in `generate'
  /Users/paulgallagher/MyGithub/heroku/rails-authlogic-rpx-sample/vendor/plugins/rails_upgrade/lib/tasks/../../lib/routes_upgrader.rb:51:in`upgrade_routes'
  /Users/paulgallagher/MyGithub/heroku/rails-authlogic-rpx-sample/vendor/plugins/rails_upgrade/lib/tasks/../../lib/routes_upgrader.rb:28:in `generate_new_routes'
  /Users/paulgallagher/MyGithub/heroku/rails-authlogic-rpx-sample/vendor/plugins/rails_upgrade/lib/tasks/rails_upgrade_tasks.rake:28
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:636:in`call'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:631:in`each'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:597:in`invoke_with_call_chain'
  /Users/paulgallagher/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/monitor.rb:242:in `synchronize'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:2051:in`invoke_task'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:2029:in`each'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:2001:in`run'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/gems/rake-0.8.7/bin/rake:31
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/bin/rake:19:in `load'
  /Users/paulgallagher/.rvm/gems/ruby-1.8.7-p302@rails235/bin/rake:19

**Comment by Maay** [comment]
Having the same problem.

**Comment by knappe** [comment]
I am too when using:

  map.root :homepage
